//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from JassParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="JassParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IJassParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile([NotNull] JassParser.FileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile([NotNull] JassParser.FileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.declr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclr([NotNull] JassParser.DeclrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.declr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclr([NotNull] JassParser.DeclrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.typedef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedef([NotNull] JassParser.TypedefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.typedef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedef([NotNull] JassParser.TypedefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.globals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobals([NotNull] JassParser.GlobalsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.globals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobals([NotNull] JassParser.GlobalsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.global_var_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobal_var_list([NotNull] JassParser.Global_var_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.global_var_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobal_var_list([NotNull] JassParser.Global_var_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.global_var_declr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobal_var_declr([NotNull] JassParser.Global_var_declrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.global_var_declr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobal_var_declr([NotNull] JassParser.Global_var_declrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.native_func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNative_func([NotNull] JassParser.Native_funcContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.native_func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNative_func([NotNull] JassParser.Native_funcContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.func_declr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_declr([NotNull] JassParser.Func_declrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.func_declr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_declr([NotNull] JassParser.Func_declrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.param_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam_list([NotNull] JassParser.Param_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.param_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam_list([NotNull] JassParser.Param_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc([NotNull] JassParser.FuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc([NotNull] JassParser.FuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.local_var_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocal_var_list([NotNull] JassParser.Local_var_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.local_var_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocal_var_list([NotNull] JassParser.Local_var_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.local_var_declr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocal_var_declr([NotNull] JassParser.Local_var_declrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.local_var_declr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocal_var_declr([NotNull] JassParser.Local_var_declrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.var_declr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_declr([NotNull] JassParser.Var_declrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.var_declr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_declr([NotNull] JassParser.Var_declrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.statement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement_list([NotNull] JassParser.Statement_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.statement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement_list([NotNull] JassParser.Statement_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] JassParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] JassParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSet([NotNull] JassParser.SetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSet([NotNull] JassParser.SetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall([NotNull] JassParser.CallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall([NotNull] JassParser.CallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgs([NotNull] JassParser.ArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgs([NotNull] JassParser.ArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.ifthenelse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfthenelse([NotNull] JassParser.IfthenelseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.ifthenelse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfthenelse([NotNull] JassParser.IfthenelseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.else_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElse_clause([NotNull] JassParser.Else_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.else_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElse_clause([NotNull] JassParser.Else_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoop([NotNull] JassParser.LoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoop([NotNull] JassParser.LoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.exitwhen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExitwhen([NotNull] JassParser.ExitwhenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.exitwhen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExitwhen([NotNull] JassParser.ExitwhenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.return_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturn_stat([NotNull] JassParser.Return_statContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.return_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturn_stat([NotNull] JassParser.Return_statContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.debug"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDebug([NotNull] JassParser.DebugContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.debug"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDebug([NotNull] JassParser.DebugContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] JassParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] JassParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.func_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_call([NotNull] JassParser.Func_callContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.func_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_call([NotNull] JassParser.Func_callContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.array_ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_ref([NotNull] JassParser.Array_refContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.array_ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_ref([NotNull] JassParser.Array_refContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.func_ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_ref([NotNull] JassParser.Func_refContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.func_ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_ref([NotNull] JassParser.Func_refContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] JassParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] JassParser.ConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.int_const"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInt_const([NotNull] JassParser.Int_constContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.int_const"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInt_const([NotNull] JassParser.Int_constContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.decimal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecimal([NotNull] JassParser.DecimalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.decimal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecimal([NotNull] JassParser.DecimalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.hex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHex([NotNull] JassParser.HexContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.hex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHex([NotNull] JassParser.HexContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.parens"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParens([NotNull] JassParser.ParensContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.parens"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParens([NotNull] JassParser.ParensContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.boolConst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolConst([NotNull] JassParser.BoolConstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.boolConst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolConst([NotNull] JassParser.BoolConstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.stringConst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringConst([NotNull] JassParser.StringConstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.stringConst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringConst([NotNull] JassParser.StringConstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] JassParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] JassParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterId([NotNull] JassParser.IdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitId([NotNull] JassParser.IdContext context);
}
