//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from JassParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="JassParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IJassParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile([NotNull] JassParser.FileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile([NotNull] JassParser.FileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.declr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclr([NotNull] JassParser.DeclrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.declr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclr([NotNull] JassParser.DeclrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.typedef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedef([NotNull] JassParser.TypedefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.typedef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedef([NotNull] JassParser.TypedefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.globals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobals([NotNull] JassParser.GlobalsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.globals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobals([NotNull] JassParser.GlobalsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.globalVarList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobalVarList([NotNull] JassParser.GlobalVarListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.globalVarList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobalVarList([NotNull] JassParser.GlobalVarListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.constDeclr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstDeclr([NotNull] JassParser.ConstDeclrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.constDeclr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstDeclr([NotNull] JassParser.ConstDeclrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.nativeFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNativeFunc([NotNull] JassParser.NativeFuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.nativeFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNativeFunc([NotNull] JassParser.NativeFuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.funcDeclr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncDeclr([NotNull] JassParser.FuncDeclrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.funcDeclr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncDeclr([NotNull] JassParser.FuncDeclrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamList([NotNull] JassParser.ParamListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamList([NotNull] JassParser.ParamListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.paramDeclr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamDeclr([NotNull] JassParser.ParamDeclrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.paramDeclr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamDeclr([NotNull] JassParser.ParamDeclrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc([NotNull] JassParser.FuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc([NotNull] JassParser.FuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.localVarList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalVarList([NotNull] JassParser.LocalVarListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.localVarList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalVarList([NotNull] JassParser.LocalVarListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.varDeclr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDeclr([NotNull] JassParser.VarDeclrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.varDeclr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDeclr([NotNull] JassParser.VarDeclrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.statementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatementList([NotNull] JassParser.StatementListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.statementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatementList([NotNull] JassParser.StatementListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] JassParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] JassParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSet([NotNull] JassParser.SetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSet([NotNull] JassParser.SetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall([NotNull] JassParser.CallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall([NotNull] JassParser.CallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgs([NotNull] JassParser.ArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgs([NotNull] JassParser.ArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.ifthenelse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfthenelse([NotNull] JassParser.IfthenelseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.ifthenelse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfthenelse([NotNull] JassParser.IfthenelseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.elseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseClause([NotNull] JassParser.ElseClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.elseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseClause([NotNull] JassParser.ElseClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoop([NotNull] JassParser.LoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoop([NotNull] JassParser.LoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.exitwhen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExitwhen([NotNull] JassParser.ExitwhenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.exitwhen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExitwhen([NotNull] JassParser.ExitwhenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.returnStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStat([NotNull] JassParser.ReturnStatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.returnStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStat([NotNull] JassParser.ReturnStatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.debug"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDebug([NotNull] JassParser.DebugContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.debug"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDebug([NotNull] JassParser.DebugContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] JassParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] JassParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncCall([NotNull] JassParser.FuncCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncCall([NotNull] JassParser.FuncCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.arrayRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayRef([NotNull] JassParser.ArrayRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.arrayRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayRef([NotNull] JassParser.ArrayRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.funcRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncRef([NotNull] JassParser.FuncRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.funcRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncRef([NotNull] JassParser.FuncRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] JassParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] JassParser.ConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.intConst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntConst([NotNull] JassParser.IntConstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.intConst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntConst([NotNull] JassParser.IntConstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.fourcc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFourcc([NotNull] JassParser.FourccContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.fourcc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFourcc([NotNull] JassParser.FourccContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.decimal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecimal([NotNull] JassParser.DecimalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.decimal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecimal([NotNull] JassParser.DecimalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.hex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHex([NotNull] JassParser.HexContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.hex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHex([NotNull] JassParser.HexContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.parens"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParens([NotNull] JassParser.ParensContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.parens"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParens([NotNull] JassParser.ParensContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.boolConst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolConst([NotNull] JassParser.BoolConstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.boolConst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolConst([NotNull] JassParser.BoolConstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.stringConst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringConst([NotNull] JassParser.StringConstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.stringConst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringConst([NotNull] JassParser.StringConstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] JassParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] JassParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JassParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterId([NotNull] JassParser.IdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JassParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitId([NotNull] JassParser.IdContext context);
}
