//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from JassParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="JassParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IJassParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] JassParser.FileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.declr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclr([NotNull] JassParser.DeclrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.typedef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypedef([NotNull] JassParser.TypedefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.globals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobals([NotNull] JassParser.GlobalsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.globalVarList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobalVarList([NotNull] JassParser.GlobalVarListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.constDeclr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstDeclr([NotNull] JassParser.ConstDeclrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.nativeFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNativeFunc([NotNull] JassParser.NativeFuncContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.funcDeclr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncDeclr([NotNull] JassParser.FuncDeclrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamList([NotNull] JassParser.ParamListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc([NotNull] JassParser.FuncContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.localVarList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalVarList([NotNull] JassParser.LocalVarListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.varDeclr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDeclr([NotNull] JassParser.VarDeclrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.statementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementList([NotNull] JassParser.StatementListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] JassParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet([NotNull] JassParser.SetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall([NotNull] JassParser.CallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgs([NotNull] JassParser.ArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.ifthenelse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfthenelse([NotNull] JassParser.IfthenelseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.elseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseClause([NotNull] JassParser.ElseClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoop([NotNull] JassParser.LoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.exitwhen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExitwhen([NotNull] JassParser.ExitwhenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.returnStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStat([NotNull] JassParser.ReturnStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.debug"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDebug([NotNull] JassParser.DebugContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] JassParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncCall([NotNull] JassParser.FuncCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.arrayRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayRef([NotNull] JassParser.ArrayRefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.funcRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncRef([NotNull] JassParser.FuncRefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] JassParser.ConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.intConst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntConst([NotNull] JassParser.IntConstContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.decimal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecimal([NotNull] JassParser.DecimalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.hex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHex([NotNull] JassParser.HexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.parens"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParens([NotNull] JassParser.ParensContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.boolConst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolConst([NotNull] JassParser.BoolConstContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.stringConst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringConst([NotNull] JassParser.StringConstContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] JassParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JassParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId([NotNull] JassParser.IdContext context);
}
